"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from pathlib import Path

import environ
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Env
env = environ.Env()
environ.Env.read_env(BASE_DIR / "env" / ".env")

ENV = env("DJANGO_ENV", default="local")
IS_PRODUCTION = ENV == "prod"

# HIGH-6: Fail-fast strict mode — refuse to start in production with insecure defaults.
if IS_PRODUCTION:
    _insecure: list[str] = []
    _secret_key = env("DJANGO_SECRETKEY", default="")
    if not _secret_key or "django-insecure" in _secret_key:
        _insecure.append("DJANGO_SECRETKEY is insecure or empty")
    if len(_secret_key) < 50:
        _insecure.append("DJANGO_SECRETKEY must be at least 50 characters in production")
    _db_pass = env("DB_PASSWORD", default="")
    if not _db_pass or _db_pass == "econ_password":
        _insecure.append("DB_PASSWORD is insecure or empty")
    if len(_db_pass) < 12:
        _insecure.append("DB_PASSWORD must be at least 12 characters in production")
    if not env("EXPECTED_JWT_ISSUER", default=""):
        _insecure.append("EXPECTED_JWT_ISSUER is not set")
    if not env("EXPECTED_JWT_AUDIENCE", default=""):
        _insecure.append("EXPECTED_JWT_AUDIENCE is not set")
    _metrics_pass = env("METRICS_BASIC_AUTH_PASSWORD", default="")
    if not _metrics_pass or _metrics_pass.startswith("CHANGE_ME"):
        _insecure.append("METRICS_BASIC_AUTH_PASSWORD is insecure or empty")
    _svc_key = env("CENTRAL_AUTH_SERVICE_KEY", default="")
    if not _svc_key or "super-secret-service-key" in _svc_key:
        _insecure.append("CENTRAL_AUTH_SERVICE_KEY is insecure or empty")
    _kafka = env("KAFKA_BOOTSTRAP_SERVERS", default="")
    _allow_localhost = env("ALLOW_LOCALHOST_IN_PROD", default="False").strip().lower() == "true"
    if not _kafka or (_kafka.startswith("localhost") and not _allow_localhost):
        _insecure.append(
            "KAFKA_BOOTSTRAP_SERVERS must use an internal service name in production "
            "(e.g. kafka:9092), not localhost. "
            "Set ALLOW_LOCALHOST_IN_PROD=True to override for local prod-mirror testing."
        )
    if _insecure:
        for _msg in _insecure:
            print(f"[FATAL] Production security check failed: {_msg}", file=sys.stderr)
        sys.exit(1)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRETKEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION

FRONTEND_URL = env("FRONTEND_URL", default="http://localhost:5173")

# HIGH-4: Lock to explicit host list. Set DJANGO_ALLOWED_HOSTS in env.
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

# Test
TESTING = "pytest" in sys.modules

# Application definition
INSTALLED_APPS = [
    # Monitoring
    "django_prometheus",
    # Local apps
    "news",
    "user_calendar",
    "exchange",
    "meta",
    "events",
    "accounts",
    "authentication.apps.AuthenticationConfig",
    "simulation",
    # Third-party
    "drf_spectacular",
    "rest_framework",
    "corsheaders",
    # default
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "common.middleware.request_id.RequestIDMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    # AuthenticationMiddleware kept for Django Admin (session-based)
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # JWKSMiddleware overrides request.user for all API paths
    "authentication.adapters.django.jwks_middleware.JWKSMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

# Keep ModelBackend for Django Admin; allauth backend removed
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# JWKS settings — Go BFF exposes the public key set at this URL
JWKS_URL = f"{env('CENTRAL_AUTH_URL', default='http://localhost:8081')}/.well-known/jwks.json"
JWKS_CACHE_TTL = 300  # seconds

# JWT issuer expected in the `iss` claim. Set to the Go BFF's issuer string.
# Required in production. Optional in local dev (warning logged if absent).
EXPECTED_JWT_ISSUER = env("EXPECTED_JWT_ISSUER", default="")

# HIGH-1: JWT audience claim verification. Set to the intended API audience string.
EXPECTED_JWT_AUDIENCE = env("EXPECTED_JWT_AUDIENCE", default="")

# HIGH-3: Basic Auth credentials for the /metrics endpoint scraped by Prometheus.
# Leave empty in dev to allow unauthenticated access; set both in production.
METRICS_BASIC_AUTH_USER = env("METRICS_BASIC_AUTH_USER", default="")
METRICS_BASIC_AUTH_PASSWORD = env("METRICS_BASIC_AUTH_PASSWORD", default="")
# Comma-separated CIDR allowlist for the Prometheus scraper IP.
# Mirrors METRICS_ALLOWED_CIDR in Central-auth Go service.
# Leave empty in dev (open access); set in production for double-lock.
METRICS_ALLOWED_CIDR = env("METRICS_ALLOWED_CIDR", default="")

# Gemini
GEMINI_API_KEY = env("GEMINI_API_KEY")
GEMINI_MODEL = env("GEMINI_MODEL")

# LLM
LLM_SERVICE_URL = env(
    "LLM_SERVICE_URL",
    default="http://localhost:8001/chat/stream",
)

# Qrant
QDRANT_URL = env("QDRANT_URL", default="http://localhost:6333")
QDRANT_COLLECTION_NEWS = env("QDRANT_COLLECTION_NEWS", default="business_news")
EMBED_MODEL_NAME = env("EMBED_MODEL_NAME", default="BAAI/bge-small-en-v1.5")
RERANK_MODEL_NAME = env("RERANK_MODEL_NAME", default="BAAI/bge-reranker-base")

# Google
GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = env("GOOGLE_CLIENT_SECRET")
GOOGLE_AUTH_REDIRECT_URI = env(
    "GOOGLE_AUTH_REDIRECT_URI",
    default="http://localhost:8000/api/auth/google/callback/",
)
GOOGLE_CALENDAR_REDIRECT_URI = env(
    "GOOGLE_CALENDAR_REDIRECT_URI",
    default="http://localhost:8000/api/calendar/oauth/callback/",
)

# Redis & Celery
REDIS_URL = env("REDIS_URL", default="redis://localhost:6380/0")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
    }
}

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True

CELERY_BEAT_SCHEDULE = {
    "fetch-business-news-every-6-hours": {
        "task": "news.tasks.fetch_business_news",
        "schedule": crontab(hour="*/6", minute=0),
    },
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # JWKSMiddleware sets request.user; this shim hands it to DRF's auth layer
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "authentication.adapters.django.jwks_middleware.MiddlewarePassthroughAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "EXCEPTION_HANDLER": "common.errors.handlers.global_exception_handler",
}

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "MyEconoCoach API",
    "VERSION": "1.0.0",
    "SECURITY": [{"BearerAuth": []}],
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
}

# React
CORS_ALLOW_CREDENTIALS = True
# CRITICAL: PROD CHANGE REQUIRED — replace localhost origins with production frontend domain
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# CRITICAL: PROD CHANGE REQUIRED — replace localhost origins with production frontend domain
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# httpOnly + samesite for refreshToken
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION

SESSION_COOKIE_SAMESITE = "Strict" if IS_PRODUCTION else "Lax"
CSRF_COOKIE_SAMESITE = "Strict" if IS_PRODUCTION else "Lax"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Central-Auth
CENTRAL_AUTH_URL = env(
    "CENTRAL_AUTH_URL",
    default="http://localhost:8081",
)

CENTRAL_AUTH_SERVICE_KEY = env("CENTRAL_AUTH_SERVICE_KEY")  # no default — fail fast if missing

CENTRAL_AUTH_TIMEOUT = env.int(
    "CENTRAL_AUTH_TIMEOUT",
    default=5,
)

# Circuit breaker settings for Central-auth and JWKS fetch calls.
# These document the intended thresholds; the values are used by
# common/resilience/circuit_breaker.py via auth_service and jwks_middleware.
CENTRAL_AUTH_CB_FAILURE_THRESHOLD = env.int("CENTRAL_AUTH_CB_FAILURE_THRESHOLD", default=5)
CENTRAL_AUTH_CB_RECOVERY_TIMEOUT = env.int("CENTRAL_AUTH_CB_RECOVERY_TIMEOUT", default=30)

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_prometheus.db.backends.postgresql",
        "NAME": env("DB_NAME", default="myeconocoach"),
        "USER": env("DB_USER", default="econ_user"),
        "PASSWORD": env("DB_PASSWORD", default="econ_password"),
        # In Docker, point at PgBouncer: DB_HOST=pgbouncer DB_PORT=5432.
        # For local dev without PgBouncer, set DB_HOST=localhost DB_PORT=5431.
        "HOST": env("DB_HOST", default="localhost"),
        "PORT": env("DB_PORT", default="5431"),
        # CRITICAL: must be 0 when routing through PgBouncer in transaction-pooling
        # mode. Django must not hold persistent connections — PgBouncer owns the pool.
        "CONN_MAX_AGE": 0,
        # CRITICAL: server-side (named) cursors require session-level state that is
        # lost between transactions under PgBouncer transaction pooling. Disable them.
        "DISABLE_SERVER_SIDE_CURSORS": True,
    }
}

# Kafka
KAFKA_BOOTSTRAP_SERVERS = env("KAFKA_BOOTSTRAP_SERVERS", default="localhost:9092")

# Password validation removed: passwords are managed by the Go BFF / Ory Identity.
# Django no longer owns user credentials.


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
